### ISSUE TITLE
Added Xcode version flag

### ISSUE THREAD

**Issue by SpottedRabbit** [alcatraz/alcatraz-packages#198]
This is a feature request. Although this may be a limited term problem, i am noticing a good number of plugins that can be installed by Alcatraz that are not compatible with Xcode 6. It is impossible to know which might work and which won't without installing and trying them out. Not horrible, but a bit more time consuming.  It would be very useful to update the config files to allow the developer to designate the compatibility of the plugin and for that info to be displayed in the GUI.

Thx

**Comment by BeauNouvelle** [comment]
This would also be handy for filtering out older plugins that no longer work with newer versions of Xcode.

**Comment by guillaume-algis** [comment]
Will be handled with https://github.com/alcatraz/Alcatraz/issues/443
