### ISSUE TITLE
add  Xcode plugin 

### ISSUE THREAD

**Issue by boyXiong** [alcatraz/alcatraz-packages#371]
Why are your packages.json data in didn't see my keys on this plugin XWJsonToCode ?

**Comment by jurre** [comment]
Sorry, I'm not sure what you mean.. Could you elaborate?

**Comment by boyXiong** [comment]
If I added to your plugin library, it should be seen in the Manager Packager of the Xcode to my plug-in, but now I can't find it.

**Comment by jurre** [comment]
I hadn't merged it, but now I have. You'll have to restart Xcode to see it, we reload the packages on startup

**Comment by boyXiong** [comment]
Okay, thank you, I have a good time with you.

**Comment by jurre** [comment]
:+1: :tada: Thanks, happy to help!

**Comment by BeauNouvelle** [comment]
Should we close this?
