### ISSUE TITLE
Plugin with pods

### ISSUE THREAD

**Issue by dvkch** [alcatraz/alcatraz-packages#376]
Hi,

It seems that a plugin that has a pod won't build, even if all schemes (pods and plugin) are set as "Shared" and it builds OK in Xcode when opening the workspace. Maybe the project is build instead of the workspace?

Stan

**Comment by jurre** [comment]
Yep, this is what happens. Unfortunately there isn't really a clean way to do this right now other than creating a build script in the project that does this, you can see an example of one here: https://github.com/markohlebar/Peckham/blob/master/Peckham.xcodeproj/project.pbxproj#L66

It's a bit of a hack and you'll have to commit your pods to the repo. We've been wanting to add support for uploading binary packages for a while now, but just haven't had the time

**Comment by dvkch** [comment]
Indeed this is unusual, but after going insane when trying to build with the pod as an included project I gave up and used this solution. Thanks a lot!!!
