### ISSUE TITLE
Plugin `Jumper` seems inactive

### ISSUE THREAD

**Issue by ricardopereira** [alcatraz/alcatraz-packages#472]
Unfortunately the `Jumper` plugin seems inactive 😔
It is something I really like to have on my Xcode.
What is the right thing to do?
Fork the project, update it and change the `packages.json` to redirect it to the forked and updated version?

**Comment by jurre** [comment]
Have you tried submitting pull requests to the original project/reaching out to the maintainer?

**Comment by ricardopereira** [comment]
Yes. I opened a PR.

**Comment by guillaumealgis** [comment]
I think at this point we could accept to replace the plugin with a fork. The original author did not reply to any request to update the plugin UUIDs.

@jurre agreed ?

**Comment by ricardopereira** [comment]
@guillaumealgis Maybe it makes more sense adapt this to support the new plugin system of Xcode 8.

**Comment by guillaumealgis** [comment]
@ricardopereira Sure! If you can port it as a new Xcode Extension that'd be awesome!

I you do, please ping here so we remove the obsolete plugin from Alcatraz :)

**Comment by ricardopereira** [comment]
https://github.com/eddiekaiger/Jumpy for Xcode 8

**Comment by ricardopereira** [comment]
Or https://github.com/deszip/Jump 😅
It's already done.
